// <auto-generated />
using System;
using BackendJobService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendJobService.Infrastructure.Migrations
{
    [DbContext(typeof(JobDbContext))]
    partial class JobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendJobService.Domain.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("cron_expression");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_run_at");

                    b.Property<DateTime?>("RunAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("run_at");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int")
                        .HasColumnName("schedule_type");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_jobs_deleted_at");

                    b.HasIndex("NextRunAt")
                        .HasDatabaseName("idx_jobs_next_run_at");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.JobExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("idx_job_executions_job_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_job_executions_status");

                    b.ToTable("job_executions", (string)null);
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.JobTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HandlerType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("handler_type");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("int")
                        .HasColumnName("max_retry_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<string>("PluginAssembly")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("plugin_assembly");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_job_tasks_deleted_at");

                    b.HasIndex("JobId", "Order")
                        .IsUnique()
                        .HasDatabaseName("uk_job_tasks_job_order");

                    b.ToTable("job_tasks", (string)null);
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.TaskExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<long>("JobExecutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_execution_id");

                    b.Property<long>("JobTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_task_id");

                    b.Property<string>("OutputJson")
                        .HasColumnType("json")
                        .HasColumnName("output_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobExecutionId")
                        .HasDatabaseName("idx_task_executions_job_execution_id");

                    b.HasIndex("JobTaskId")
                        .HasDatabaseName("idx_task_executions_job_task_id");

                    b.ToTable("task_executions", (string)null);
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.JobExecution", b =>
                {
                    b.HasOne("BackendJobService.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.JobTask", b =>
                {
                    b.HasOne("BackendJobService.Domain.Entities.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.TaskExecution", b =>
                {
                    b.HasOne("BackendJobService.Domain.Entities.JobExecution", "JobExecution")
                        .WithMany("TaskExecutions")
                        .HasForeignKey("JobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendJobService.Domain.Entities.JobTask", "JobTask")
                        .WithMany()
                        .HasForeignKey("JobTaskId");

                    b.Navigation("JobExecution");

                    b.Navigation("JobTask");
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.Job", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BackendJobService.Domain.Entities.JobExecution", b =>
                {
                    b.Navigation("TaskExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
